apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: nginx-server
spec:
 generators:
 - list:
     elements:
     - cluster: dev
       url: https://kubernetes.default.svc
 template:
   metadata:
     name: '{{cluster}}-nginx-server'
   spec:
     project: default
     source:
       helm:
         values: |
            replicaCount: 3
              
         releaseName: nginx
       repoURL: https://github.com/mato2/helm-charts.git
       targetRevision: HEAD
       path: test-apps
     destination:
        server: https://kubernetes.default.svc
        namespace: nginx
     syncPolicy:
       automated:
         prune: true
         selfHeal: true