apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/secrets.yaml
- base/applications.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.2/manifests/ha/install.yaml

patchesStrategicMerge:
- overlays/service.yaml

patchesJson6902:
- path: overlays/deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocds